#!/bin/sh /etc/rc.common
START=50

run_njit()
{
	local enable
	config_get_bool enable $1 enable
	
	if [ $enable ]; then
		local username
		local password
		local ifname
		
		config_get username $1 username
		config_get password $1 password
		config_get ifname $1 ifname
		
		result=1
		while [ $result -eq 1 ]
		do
			wanip=$(ifconfig $ifname 2> /dev/null | grep 'inet addr' | awk '{print $2}' | cut -d: -f2)
			if [ "$wanip" = "" ]||[ "$wanip" = "0.0.0.0" ]; then
				ifup wan
				sleep 5
			else
				result=0
			fi
		done
	
		sleep 3
		
		njit-client $username $password $ifname >/dev/null 2>&1 &
		
		echo "NJIT Client has started."
	fi
}

start()
{
	config_load njitclient
	config_foreach run_njit login
}

stop()
{
	if [ -n "`pidof njit-client`" ] ; then
		kill -9 "`pidof njit-client`"
		sleep 3
	fi

	echo "NJIT Client has stoped."
}
